services:
  backend:
    build:
      context: .
      dockerfile: Backend.Dockerfile
    depends_on:
      - mongo
    env_file:
      - backend/.env
    networks:
      - backend-network
    restart: unless-stopped

  next:
    build:
      context: .
      dockerfile: Next.Dockerfile
    env_file:
      - .env
    networks:
      - backend-network
    restart: unless-stopped

  nginx:
    image: nginx:1.27.4-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - next
    networks:
      - backend-network
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    networks:
      - backend-network
    volumes:
      - db-data:/data/db
    restart: unless-stopped

volumes:
  db-data:

networks:
  backend-network:
