stages:
  - build
  - test
  - deliver
  - run

build-ai-pipeline:
  stage: build
  image: gradle:8.13.0-jdk21
  script:
    - chmod +x ./gradlew
    - ./gradlew :shared:build
    - ./gradlew :aipipeline:build
    - ./gradlew :documentimporter:build -x test
    - ./gradlew :persistenceService:build -x test
    - ls -R src/services/aiPipeline/AIPipeline/build/libs
  artifacts:
    paths:
      - src/services/aiPipeline/AIPipeline/build/libs/*.jar
      - src/services/documentImporter/DocumentImporter/build/libs/*.jar
      - src/services/persistenceService/PersistenceService/build/libs/*.jar

test-scanner:
  stage: test
  image: gradle:8.13.0-jdk21
  script:
    - cd src/services/aiPipeline/AIPipeline
    - chmod +x ./gradlew
    - echo "compiling and creating deployable artifact"
    - ./gradlew check sonar -info
    - cat ./build/jacocoHtml/index.html | grep -o '<tfoot>.*</tfoot>'
  coverage: "/Total.*?([0-9]{1,3})%/"

deliver-ai-pipeline:
  stage: deliver
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker pull eclipse-temurin:21-jre
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  dependencies:
    - build-ai-pipeline
  script:
    - cd src/services/aiPipeline/AIPipeline
    - VERSION_TAG=$(date +'%Y%m%d')
    - IMAGE_TAG="$CI_REGISTRY_IMAGE:$VERSION_TAG"
    - docker build -t "$IMAGE_TAG" .
    - docker tag "$IMAGE_TAG" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$IMAGE_TAG"
    - docker push "$CI_REGISTRY_IMAGE:latest"
    - docker logout $CI_REGISTRY

deliver-run-docker-compose:
  needs:
    - deliver-ai-pipeline
    - build-ai-pipeline
  image: docker:latest
  stage: run
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --no-cache bash
    - mkdir -p /tmp/pdf_input
  script:
    - cd src/services/aiPipeline/AIPipeline
    #    - #cp example.env .env
    - echo "Starting containers with docker-compose..."
    - IMAGE_TAG="$CI_REGISTRY_IMAGE:latest"
    - echo "Starting containers with docker-compose..."
    - docker-compose pull
    - docker-compose up -d
    - sleep 10
    - docker-compose ps
    - docker-compose logs
    - echo "Validating service functionality..."
    - docker-compose down || true
    - docker logout $CI_REGISTRY || true
